{
  "cells": [
    {
      "cell_type": "code",
      "metadata": {},
      "source": [
        "import numpy as np\n",
        "\n",
        "def sigmoid(x):\n",
        "    \"\"\"\n",
        "    Sigmoid activation function\n",
        "    :param x: input value (float or np.array)\n",
        "    :return: sigmoid of x\n",
        "    \"\"\"\n",
        "    return 1.0 / (1.0 + np.exp(-x))\n",
        "\n",
        "def dsigmoid(x):\n",
        "    \"\"\"\n",
        "    Derivative of the sigmoid function\n",
        "    :param x: input value (float or np.array); x is the output of sigmoid\n",
        "    :return: derivative of sigmoid at x\n",
        "    \"\"\"\n",
        "    return x * (1.0 - x)\n",
        "\n",
        "def tanh(x):\n",
        "    \"\"\"\n",
        "    Hyperbolic tangent activation function\n",
        "    :param x: input value (float or np.array)\n",
        "    :return: tanh of x\n",
        "    \"\"\"\n",
        "    return np.tanh(x)\n",
        "\n",
        "def dtanh(x):\n",
        "    \"\"\"\n",
        "    Derivative of the hyperbolic tangent function\n",
        "    :param x: input value (float or np.array); x is the output of tanh\n",
        "    :return: derivative of tanh at x\n",
        "    \"\"\"\n",
        "    return 1.0 - x**2\n",
        "\n",
        "class NeuralNetwork:\n",
        "    \"\"\"\n",
        "    A simple fully-connected neural network implementation.\n",
        "    Allows multiple hidden layers with a specified number of neurons each.\n",
        "    Provides options for activation function: sigmoid or tanh.\n",
        "    Includes bias neurons.\n",
        "    \"\"\"\n",
        "    def __init__(self, input_size, hidden_layers, hidden_neurons, output_size,\n",
        "                 activation='sigmoid', learning_rate=0.1, epochs=10000):\n",
        "        \"\"\"\n",
        "        Initialize the neural network.\n",
        "\n",
        "        :param input_size: number of input neurons (excluding bias)\n",
        "        :param hidden_layers: integer, how many hidden layers\n",
        "        :param hidden_neurons: list of integers specifying the number of neurons in each hidden layer\n",
        "        :param output_size: number of output neurons\n",
        "        :param activation: 'sigmoid' or 'tanh'\n",
        "        :param learning_rate: learning rate (float)\n",
        "        :param epochs: number of training epochs (integer)\n",
        "        \"\"\"\n",
        "        self.input_size = input_size\n",
        "        self.hidden_layers = hidden_layers\n",
        "        self.hidden_neurons = hidden_neurons\n",
        "        self.output_size = output_size\n",
        "        self.learning_rate = learning_rate\n",
        "        self.epochs = epochs\n",
        "\n",
        "        # Select activation function\n",
        "        if activation == 'sigmoid':\n",
        "            self.activation = sigmoid\n",
        "            self.activation_deriv = dsigmoid\n",
        "        else:\n",
        "            self.activation = tanh\n",
        "            self.activation_deriv = dtanh\n",
        "\n",
        "        # Create a list of layer sizes: input -> hidden layers -> output\n",
        "        layer_sizes = [self.input_size] + self.hidden_neurons + [self.output_size]\n",
        "\n",
        "        # Initialize weights (with bias) for each layer:\n",
        "        # Example: if layer_sizes = [2, 4, 1], we have:\n",
        "        #   - weights[0] is shape (4, 3) for connecting input layer(2) + bias(1) -> hidden layer(4)\n",
        "        #   - weights[1] is shape (1, 5) for connecting hidden layer(4) + bias(1) -> output layer(1)\n",
        "\n",
        "        self.weights = []\n",
        "        for i in range(len(layer_sizes)-1):\n",
        "            w = np.random.uniform(-0.05, 0.05, (layer_sizes[i+1], layer_sizes[i] + 1))\n",
        "            self.weights.append(w)\n",
        "\n",
        "    def forward(self, X):\n",
        "        \"\"\"\n",
        "        Forward pass through the network.\n",
        "        :param X: input array of shape (n_features, ) for a single sample\n",
        "        :return: (list_of_z, list_of_a) containing pre-activations(z) and activations(a) for each layer\n",
        "        \"\"\"\n",
        "        # Convert X to a column vector if needed\n",
        "        if len(X.shape) == 1:\n",
        "            X = X.reshape(-1, 1)\n",
        "\n",
        "        z_values = []  # pre-activation values\n",
        "        a_values = []  # activation values\n",
        "\n",
        "        # The activation of the input layer is just X (flattened) but we add bias = 1\n",
        "        a = np.vstack((X, [[1]]))  # shape (input_size+1, 1)\n",
        "        a_values.append(a)\n",
        "\n",
        "        # Forward pass through each layer\n",
        "        for w in self.weights:\n",
        "            z = np.dot(w, a)  # shape = (layer_size, 1)\n",
        "            a_no_bias = self.activation(z)  # shape = (layer_size, 1)\n",
        "            z_values.append(z)\n",
        "            # Add bias to the activation except for the output layer\n",
        "            if w is not self.weights[-1]:\n",
        "                a = np.vstack((a_no_bias, [[1]]))\n",
        "            else:\n",
        "                a = a_no_bias\n",
        "            a_values.append(a)\n",
        "\n",
        "        return z_values, a_values\n",
        "\n",
        "    def backward(self, z_values, a_values, y):\n",
        "        \"\"\"\n",
        "        Backward pass (backpropagation).\n",
        "        :param z_values: list of pre-activation values for each layer\n",
        "        :param a_values: list of activation values for each layer\n",
        "        :param y: target value (scalar or vector)\n",
        "        :return: list of gradients for each weight matrix\n",
        "        \"\"\"\n",
        "        # Convert y to the same shape as output layer if it's scalar\n",
        "        if isinstance(y, (int, float)):\n",
        "            y = np.array([[y]])\n",
        "        else:\n",
        "            y = y.reshape(-1,1)\n",
        "\n",
        "        # Initialize list of deltas\n",
        "        deltas = [None] * len(self.weights)\n",
        "\n",
        "        # The activation at the output layer is the last in a_values\n",
        "        a_output = a_values[-1]  # shape (output_size, 1)\n",
        "\n",
        "        # 1) Output layer delta\n",
        "        error = (a_output - y)  # shape (output_size, 1)\n",
        "        if len(z_values) > 0:\n",
        "            # derivative w.r.t. z_output\n",
        "            delta_output = error * self.activation_deriv(a_output)\n",
        "        else:\n",
        "            delta_output = error  # in case there's no hidden layer\n",
        "        deltas[-1] = delta_output\n",
        "\n",
        "        # 2) Hidden layers delta (if any)\n",
        "        # We go backwards from second to last layer to the first layer\n",
        "        for i in range(len(self.weights) - 2, -1, -1):\n",
        "            w_next = self.weights[i+1]\n",
        "            # remove the bias row from next layer weights if needed\n",
        "            w_next_no_bias = w_next[:, :-1]  # shape: (layer_{i+1}, layer_i)\n",
        "            delta_up = deltas[i+1]  # shape: (layer_{i+1}, 1)\n",
        "\n",
        "            # activation of layer i (a_values[i+1] includes bias if not the output)\n",
        "            a_i = a_values[i+1]\n",
        "            if i < len(self.weights) - 2:\n",
        "                # if not the last hidden layer, then a_i includes the bias as last row\n",
        "                a_i_no_bias = a_i[:-1]\n",
        "            else:\n",
        "                # for the hidden layer just before the output, a_i has no extra bias row if there's only one hidden layer\n",
        "                if a_i.shape[0] > w_next_no_bias.shape[1]:\n",
        "                    a_i_no_bias = a_i[:-1]\n",
        "                else:\n",
        "                    a_i_no_bias = a_i\n",
        "\n",
        "            # we need the derivative of a_i (which is activation), so use activation_deriv\n",
        "            delta_i = (w_next_no_bias.T @ delta_up) * self.activation_deriv(a_i_no_bias)\n",
        "            deltas[i] = delta_i\n",
        "\n",
        "        # Now compute gradients for each layer's weights\n",
        "        grads = []\n",
        "        for i, w in enumerate(self.weights):\n",
        "            # Activation of previous layer\n",
        "            a_prev = a_values[i]  # shape: (layer_size + 1, 1)\n",
        "            # delta for current layer\n",
        "            delta_i = deltas[i]  # shape: (layer_size, 1)\n",
        "            # gradient is delta_i * a_prev^T\n",
        "            grad_i = delta_i @ a_prev.T  # shape: same as w\n",
        "            grads.append(grad_i)\n",
        "\n",
        "        return grads\n",
        "\n",
        "    def update_weights(self, grads):\n",
        "        \"\"\"\n",
        "        Update weights by gradient descent step.\n",
        "        :param grads: list of gradients for each layer\n",
        "        \"\"\"\n",
        "        for i in range(len(self.weights)):\n",
        "            self.weights[i] -= self.learning_rate * grads[i]\n",
        "\n",
        "    def fit(self, X, y):\n",
        "        \"\"\"\n",
        "        Train (fit) the neural network on the given data.\n",
        "        :param X: input data, shape (n_samples, n_features)\n",
        "        :param y: target data, shape (n_samples,) or (n_samples, 1)\n",
        "        \"\"\"\n",
        "        for epoch in range(self.epochs):\n",
        "            # We'll do batch gradient descent for simplicity on these tiny datasets.\n",
        "            total_grad = [np.zeros_like(w) for w in self.weights]\n",
        "\n",
        "            for i in range(len(X)):\n",
        "                x_sample = X[i]\n",
        "                y_sample = y[i]\n",
        "                z_values, a_values = self.forward(x_sample)\n",
        "                grads = self.backward(z_values, a_values, y_sample)\n",
        "                # accumulate\n",
        "                for j in range(len(total_grad)):\n",
        "                    total_grad[j] += grads[j]\n",
        "\n",
        "            # After summing gradients over the entire dataset, update\n",
        "            for j in range(len(total_grad)):\n",
        "                total_grad[j] /= len(X)\n",
        "\n",
        "            self.update_weights(total_grad)\n",
        "\n",
        "    def predict(self, X):\n",
        "        \"\"\"\n",
        "        Predict outputs for given input X.\n",
        "        :param X: input array of shape (n_samples, n_features)\n",
        "        :return: predictions array of shape (n_samples, )\n",
        "        \"\"\"\n",
        "        preds = []\n",
        "        for i in range(len(X)):\n",
        "            _, a_values = self.forward(X[i])\n",
        "            preds.append(a_values[-1].flatten())  # last layer's activation\n",
        "        return np.array(preds).squeeze()\n",
        "\n",
        "def get_boolean_data(func_name):\n",
        "    \"\"\"\n",
        "    Return the input-output pairs for a given boolean function with 2 inputs.\n",
        "    :param func_name: 'AND', 'OR', 'XOR'\n",
        "    :return: (X, y) where X.shape = (4,2), y.shape=(4,)\n",
        "    \"\"\"\n",
        "    X = np.array([\n",
        "        [0, 0],\n",
        "        [0, 1],\n",
        "        [1, 0],\n",
        "        [1, 1]\n",
        "    ])\n",
        "\n",
        "    if func_name == 'AND':\n",
        "        y = np.array([0, 0, 0, 1])\n",
        "    elif func_name == 'OR':\n",
        "        y = np.array([0, 1, 1, 1])\n",
        "    elif func_name == 'XOR':\n",
        "        y = np.array([0, 1, 1, 0])\n",
        "    else:\n",
        "        raise ValueError(\"Unknown boolean function: \"+func_name)\n",
        "\n",
        "    return X, y\n",
        "\n",
        "def train_and_test_boolean_function(func_name, activation, hidden_layers, hidden_neurons,\n",
        "                                    learning_rate=0.1, epochs=10000):\n",
        "    \"\"\"\n",
        "    Train a neural network to learn a boolean function and return the predictions.\n",
        "    :param func_name: 'AND', 'OR', or 'XOR'\n",
        "    :param activation: 0 for sigmoid, 1 for tanh\n",
        "    :param hidden_layers: number of hidden layers (int)\n",
        "    :param hidden_neurons: list of ints specifying #neurons in each hidden layer\n",
        "    :param learning_rate: float, learning rate\n",
        "    :param epochs: number of training epochs\n",
        "    :return: list of outputs for each of the 4 possible inputs\n",
        "    \"\"\"\n",
        "    # Prepare data\n",
        "    X, y = get_boolean_data(func_name)\n",
        "\n",
        "    # Activation function choice\n",
        "    if activation == 0:\n",
        "        activation_str = 'sigmoid'\n",
        "    else:\n",
        "        activation_str = 'tanh'\n",
        "\n",
        "    # Build NN\n",
        "    nn = NeuralNetwork(\n",
        "        input_size=2,\n",
        "        hidden_layers=hidden_layers,\n",
        "        hidden_neurons=hidden_neurons,\n",
        "        output_size=1,\n",
        "        activation=activation_str,\n",
        "        learning_rate=learning_rate,\n",
        "        epochs=epochs\n",
        "    )\n",
        "\n",
        "    # Train\n",
        "    nn.fit(X, y)\n",
        "\n",
        "    # Test\n",
        "    predictions = nn.predict(X)\n",
        "    return predictions\n",
        "\n",
        "def run_demo(boolean_func, activation_flag, hidden_layers, hidden_neurons):\n",
        "    \"\"\"\n",
        "    Trains the NN on user-specified boolean functions (AND, OR, XOR or ALL) and prints the results.\n",
        "    :param boolean_func: 'AND', 'OR', 'XOR' or 'ALL'\n",
        "    :param activation_flag: 0 for sigmoid, 1 for tanh\n",
        "    :param hidden_layers: number of hidden layers (int)\n",
        "    :param hidden_neurons: list of ints specifying #neurons in each hidden layer\n",
        "    \"\"\"\n",
        "    if boolean_func == 'ALL':\n",
        "        funcs = ['AND', 'OR', 'XOR']\n",
        "    else:\n",
        "        funcs = [boolean_func]\n",
        "\n",
        "    for f in funcs:\n",
        "        preds = train_and_test_boolean_function(\n",
        "            func_name=f,\n",
        "            activation=activation_flag,\n",
        "            hidden_layers=hidden_layers,\n",
        "            hidden_neurons=hidden_neurons,\n",
        "            learning_rate=0.1,\n",
        "            epochs=10000\n",
        "        )\n",
        "        # Print results\n",
        "        print(f\"\\n{f}:\")\n",
        "        X = [[0,0],[0,1],[1,0],[1,1]]\n",
        "        for i, inp in enumerate(X):\n",
        "            print(f\"{tuple(inp)} -> {preds[i]:.4f}\")\n",
        "\n",
        "# Example usage (uncomment the lines below to run in Jupyter):\n",
        "# run_demo(\n",
        "#    boolean_func='ALL',  # could be 'AND', 'OR', 'XOR', or 'ALL'\n",
        "#    activation_flag=0,   # 0 for sigmoid, 1 for tanh\n",
        "#    hidden_layers=1,     # number of hidden layers\n",
        "#    hidden_neurons=[4]   # list of neuron counts for each hidden layer\n",
        "#)\n",
        "\n",
        "print(\"Neural Network code loaded. You can call run_demo(...) to train/test.\")\n",
        "print(\"\\nSignificance of 'bias' neuron: Each layer in the network (except for the input layer) typically has an additional \")\n",
        "print(\"parameter that acts as a constant offset to help the activations shift. This is implemented as an extra column in \")\n",
        "print(\"the weight matrix, effectively a 'bias neuron'. It does not count towards the user-specified number of neurons, but \")\n",
        "print(\"it is always added internally for each layer.\")\n"
      ],
      "execution_count": null,
      "outputs": []
    }
  ],
  "metadata": {
    "name": "NeuralNetworkBooleanFunctions",
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3",
      "language": "python"
    },
    "language_info": {
      "name": "python",
      "version": "3.8"
    }
  },
  "nbformat": 4,
  "nbformat_minor": 4
}
